# Generated by Django 6.0.4 on 2026-04-23 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='KitModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_kit', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kit Modelo',
                'verbose_name_plural': 'Kits Modelos',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=20, unique=True)),
                ('data_programada', models.DateField()),
                ('tipo', models.CharField(choices=[('INSTALACAO', 'Instalação'), ('MANUTENCAO', 'Manutenção'), ('PADRAO', 'Padrão Concessionária')], default='INSTALACAO', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RUA', 'Em Rua'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=20)),
                ('cliente', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sku_codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('PAR', 'Par'), ('KIT', 'Kit')], default='UN', max_length=3)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_minima', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SAIDA_OS', 'Saída para OS'), ('RETORNO_OS', 'Retorno de OS'), ('COMPRA', 'Entrada por Compra'), ('AJUSTE', 'Ajuste de Inventário')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.ordemservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='ItemOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_saida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_retorno', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('obs_editado', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.ordemservico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Item da OS',
                'verbose_name_plural': 'Itens da OS',
            },
        ),
        migrations.CreateModel(
            name='ItemKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.kitmodelo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
