# Generated by Django 6.0.4 on 2026-04-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='kit_referencia',
            field=models.ForeignKey(blank=True, help_text='Selecione um kit para carregar os itens automaticamente. Você poderá editar as quantidades depois.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.kitmodelo'),
        ),
        migrations.AlterField(
            model_name='itemos',
            name='obs_editado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='itemos',
            name='quantidade_retorno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qtd Retorno'),
        ),
        migrations.AlterField(
            model_name='itemos',
            name='quantidade_saida',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtd Saída'),
        ),
    ]
