# Generated by Django 6.0.4 on 2026-04-23 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_produto_options_ordemservico_kit_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemos',
            name='obs_editado',
        ),
        migrations.RemoveField(
            model_name='itemos',
            name='quantidade_retorno',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_custo',
        ),
        migrations.AlterField(
            model_name='itemos',
            name='quantidade_saida',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada de Fornecedor'), ('RETORNO_GERAL', 'Retorno Geral de Campo (Sobras)'), ('SAIDA_OS', 'Saída Automática (OS)'), ('AJUSTE', 'Ajuste de Inventário')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='kit_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.kitmodelo'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente (No Galpão)'), ('RUA', 'Em Rua (Material Saiu)'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=20),
        ),
    ]
