# Generated by Django 6.0.4 on 2026-04-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_itemos_obs_editado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemos',
            options={},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='numero_nota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_COMPRA', 'Entrada de Fornecedor (Nota Fiscal)'), ('RETORNO_GERAL', 'Retorno Geral de Campo (Sobras)'), ('SAIDA_OS', 'Saída Automática (OS)'), ('AJUSTE', 'Ajuste de Inventário')], max_length=30),
        ),
    ]
