# Generated by Django 6.0.4 on 2026-04-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_itemos_options_movimentacao_numero_nota_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemos',
            options={'verbose_name': 'Item da OS', 'verbose_name_plural': 'Itens da OS'},
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='kit_referencia',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='kits_aplicados',
            field=models.ManyToManyField(blank=True, help_text='Selecione os kits necessários (ex: Kit Usina + Kit Ligação Aérea)', to='estoque.kitmodelo'),
        ),
        migrations.AlterField(
            model_name='kitmodelo',
            name='descricao',
            field=models.TextField(blank=True, help_text='Ex: Kit Fixo 10 itens ou Kit Ligação Aérea'),
        ),
    ]
