# Generated by Django 6.0.4 on 2026-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_produto_preco_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço da Instalação'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnico Responsável'),
        ),
    ]
