# Generated by Django 6.0.4 on 2026-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_ordemservico_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitmodelo',
            name='descricao',
            field=models.TextField(blank=True, help_text='Ex: Kit Fixo ou Kit Ligação Aérea'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='kits_aplicados',
            field=models.ManyToManyField(blank=True, help_text='Selecione os kits necessários', to='estoque.kitmodelo'),
        ),
    ]
